### ISSUE TITLE
Doesn't work when using esbuild's `stdin`

### ISSUE THREAD

**Issue by ayoreis** [lucacasonato/esbuild_deno_loader#18]
Windows 11, Deno 1.24.0, https://deno.land/x/esbuild@v0.14.49, https://deno.land/x/esbuild_deno_loader@0.5.0

```ts
// greetings.ts
export function sayWelcome(name: string) {
    return `Welcome ${name}!`
}

// welcome.ts 
import { sayWelcome } from './greetings.ts'

console.log(sayWelcome('Luca'))
```

But `welcome.ts` is passed to esbuild by [stdin](https://esbuild.github.io/api/#stdin) with these settings:
```ts
esbuild.build({
    // ...

    stdin: {
        contents: await Deno.readTextFile('./welcome.ts'),
        resolveDir: Deno.cwd(),
        sourcefile: 'welcome.ts',
        loader: 'ts',
    }

    // ...
})
```

```
X [ERROR] [plugin deno] Invalid URL

    welcome.ts:1:27:
      1 │ import { sayWelcome } from './greetings.ts'
        ╵                            ~~~~~~~~~~~~~~~~

error: Uncaught (in promise) Error: Build failed with 1 error:
welcome.ts:1:27: ERROR: [plugin: deno] Invalid URL
    {
      detail: TypeError: Invalid URL
        at Object.opSync (deno:core/01_core.js:170:12)
        at opUrlParse (deno:ext/url/00_url.js:49:27)
        at new URL (deno:ext/url/00_url.js:323:20)
        at onResolve (https://deno.land/x/esbuild_deno_loader@0.5.0/mod.ts:68:22)
        at callback (https://deno.land/x/esbuild@v0.14.49/mod.js:904:34)
        at handleRequest (https://deno.land/x/esbuild@v0.14.49/mod.js:684:36)
        at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.49/mod.js:739:7)
        at readFromStdout (https://deno.land/x/esbuild@v0.14.49/mod.js:615:7)
        at https://deno.land/x/esbuild@v0.14.49/mod.js:1867:11,
      id: "",
      location: {
        column: 27,
        file: "welcome.ts",
        length: 16,
        line: 1,
        lineText: "import { sayWelcome } from './greetings.ts'",
        namespace: "",
        suggestion: ""
      },
      notes: [],
      pluginName: "deno",
      text: "Invalid URL"
    }
  let error = new Error(`${text}${summary}`);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.49/mod.js:1588:15)
    at https://deno.land/x/esbuild@v0.14.49/mod.js:1234:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.49/mod.js:1017:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.49/mod.js:1232:7)
    at https://deno.land/x/esbuild@v0.14.49/mod.js:1341:14
    at https://deno.land/x/esbuild@v0.14.49/mod.js:649:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.49/mod.js:746:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.49/mod.js:615:7)
    at https://deno.land/x/esbuild@v0.14.49/mod.js:1867:11
```

**Comment by lucacasonato** [comment]
`sourcefile` must be set to a fully qualified URL (`file:///User/me/welcome.ts`).

**Comment by ayoreis** [comment]
Thanks. Is this specific to esbuild_deno_loader? In the docs it shows setting it as I did: https://esbuild.github.io/api/#stdin.

**Comment by jsejcksn** [comment]
@lucacasonato I encountered this issue, too. I continued to see the same error until I also deleted the property at `buildOptions.stdin.resolveDir`. Is that expected?
