### ISSUE TITLE
error: [plugin: deno] Unreachable

### ISSUE THREAD

**Issue by fibo** [lucacasonato/esbuild_deno_loader#2]
Given a file `module.ts`

```typescript
import { assetsBaseUrl } from "ggbot2-assets";
console.log(assetsBaseUrl);
```

And a file `build.ts`

```typescript
import * as esbuild from "esbuild";
import { denoPlugin } from "esbuild_deno_loader";

await esbuild.build({
  plugins: [denoPlugin({ importMapFile: "./import_map.json" })],
  entryPoints: ["./module.ts"],
  outfile: "./module.js",
  bundle: true,
  minify: true,
  format: "esm",
});
esbuild.stop();
```

Where `import_map.json` is the following

```json
{
  "imports": {
    "esbuild": "https://deno.land/x/esbuild@v0.12.28/mod.js",
    "esbuild_deno_loader": "https://deno.land/x/esbuild_deno_loader@0.3.0/mod.ts",
    "ggbot2-assets": "https://github.com/ggbot2/assets/raw/main/index.ts"
  }
}
```

Running the module works, try it with

    deno run --unstable --importmap=import_map.json module.ts

But the build raises the following issue

```
 > deno:file:///Users/gcasati/github.com/ggbot2/test/module.ts:1:30: error: [plugin: deno] Unreachable.
    1 │ import { assetsBaseUrl } from "ggbot2-assets";
      ╵                               ~~~~~~~~~~~~~~~

error: Uncaught (in promise) Error: Build failed with 1 error:
deno:file:///Users/gcasati/github.com/ggbot2/test/module.ts:1:30: error: [plugin: deno] Unreachable.
  let error = new Error(`${text}${summary}`);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.12.28/mod.js:1436:15)
    at https://deno.land/x/esbuild@v0.12.28/mod.js:1094:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.12.28/mod.js:882:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.12.28/mod.js:1092:7)
    at https://deno.land/x/esbuild@v0.12.28/mod.js:1201:14
    at https://deno.land/x/esbuild@v0.12.28/mod.js:570:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.12.28/mod.js:667:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.12.28/mod.js:537:7)
    at https://deno.land/x/esbuild@v0.12.28/mod.js:1706:11
```

To run build launch command

    deno run --unstable --importmap=import_map.json --allow-env --allow-read --allow-net --allow-run --allow-write ./build.ts

**Comment by okikio** [comment]
The URL you are using is invalid https://github.com/ggbot2/assets/raw/main/index.ts
![image](https://user-images.githubusercontent.com/17222836/162588884-bd920e8f-e74d-48b6-8f41-da602a7cc1e9.png)

**Comment by fibo** [comment]
@okikio yes I removed it.

It was not working at the time it was reported but it does not matter now, let's close this issue.
