### ISSUE TITLE
Invalid cross-device link when shipping npm specified modules to browser

### ISSUE THREAD

**Issue by ewired** [lucacasonato/esbuild_deno_loader#76]
Bundling in Fresh with npm specifiers has this issue when /tmp and home are on two different filesystems:
```
      detail: Error: Invalid cross-device link (os error 18): link '/var/home/ewired/.cache/deno/npm/registry.npmjs.org/preact/10.15.1/LICENSE' -> '/tmp/68aa0db9/LICENSE'
    at async Object.link (ext:deno_fs/30_fs.js:401:3)
    at async linkRecursive (https://deno.land/x/esbuild_deno_loader@0.8.1/src/loader_native.ts:165:5)
    at async linkRecursive (https://deno.land/x/esbuild_deno_loader@0.8.1/src/loader_native.ts:162:7)
    at async NativeLoader.#nodeModulesDirForPackageInner (https://deno.land/x/esbuild_deno_loader@0.8.1/src/loader_native.ts:126:5)
    at async NativeLoader.nodeModulesDirForPackage (https://deno.land/x/esbuild_deno_loader@0.8.1/src/loader_native.ts:80:17)
    at async onResolve (https://deno.land/x/esbuild_deno_loader@0.8.1/src/plugin_deno_loader.ts:261:28)
    at async requestCallbacks.on-resolve (https://deno.land/x/esbuild@v0.17.19/mod.js:1336:22)
    at async handleRequest (https://deno.land/x/esbuild@v0.17.19/mod.js:699:13) {
        code: "EXDEV"
```

**Comment by ngasull** [comment]
Ran into this as well and spotted 2 issues

## Hard link
Fails as it doesn't make sense when pointing on separate filesystems. 

If keeping the hardlink strategy, I see only 2 solutions :

1. Making a custom temporary folder directly inside `DENO_DIR`.
2. Falling back with a separate copy-based strategy

## Rename
Fails because `Deno.rename` just runs the underlying syscall.

`std/fs` has `move` but it actually doesn't handle separate file systems. This has been noticed recently and there's a [PR on `Deno.rename`](https://github.com/denoland/deno/pull/19879) but [Ryan goes in the direction of including the case in `std`](https://github.com/denoland/deno_std/issues/1070#issuecomment-887872823), which makes sense.

Anyhow, solving the rename won't solve the hard link strategy !

**Comment by ngasull** [comment]
I actually followed up with solution 1. :point_right: https://github.com/lucacasonato/esbuild_deno_loader/pull/79

@ewired you may solve your issue by temporarily importing from my fork as well
<details>
  <summary>Use at your own risk :upside_down_face: </summary>

```ts
import { denoPlugins } from "https://raw.githubusercontent.com/ngasull/esbuild_deno_loader/0144b46ceca6324c55b6246018000f81e09ec631/mod.ts";
```
</details>
