### ISSUE TITLE
Using with Deno Deploy

### ISSUE THREAD

**Issue by adoublef** [lucacasonato/esbuild_deno_loader#88]
I wanted to learn how to setup `esbuild` within Deno Deploy. I have tried the example as stated in the README but I keep getting the following errors

```
ReferenceError: Worker is not defined
    at startRunningService (https://deno.land/x/esbuild@v0.19.2/wasm.js:1777:5)
    at ensureServiceIsRunning (https://deno.land/x/esbuild@v0.19.2/wasm.js:1758:31)
    at Module.build (https://deno.land/x/esbuild@v0.19.2/wasm.js:1734:26)
    at file:///src/main.ts:8:30
```

I have tried using the `v0.19.2` version of the wasm esbuild (which looks to give me a deno-ts error saying the versions are not compatible) as well as `v0.17.19` not working.

Would like to know what I ought to do to resolve 
[link to repo here](https://github.com/adoublef/geode-save)
[link to deployed app here](https://geode-save.deno.dev/)

**Comment by AlexJeffcott** [comment]
I suspect that the deno-ts error would be resolved by https://github.com/lucacasonato/esbuild_deno_loader/pull/78 but for some reason the maintainer has not deployed it.

**Comment by cowboyd** [comment]
I'm also seeing this error when trying to use esbuild on Deno Deploy.
